name: 'PathFinderAPI'
version: '${project.version}'
main: com.tcc.pathfinderapi.PathFinderAPI
api-version: 1.19
authors: [ kwilk, StarbuckBarista ]
description: 'Developer utility to find and generate paths between locations or entities.'

commands:
  pathapi find:
    description: 'Finds a path between two locations.'
    usage: 'Usage: /pathapi find [Start; X Y Z] [End; X Y Z]'

permissions:
  pathapi.find:
    description: 'Allows usage of the /pathapi find command.'
    default: op
